name: intl_messages
description: Simple and easy internationalization and localization messages.
version: 1.1.3
homepage: https://github.com/gmpassos/intl_messages

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  intl: ^0.16.1
  resource_portable: ^2.1.6
  enum_to_string: ^1.0.8
  swiss_knife: ^2.2.1
    #path: ../swiss_knife

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
