name: intl_messages
description: Simple and easy internationalization and localization messages.
version: 1.1.0
homepage: https://github.com/gmpassos/intl_messages
author: gmpassos <gracilianomp@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  intl: ^0.15.7
  resource: ^2.1.6
  enum_to_string: ^1.0.7
  swiss_knife: ^2.1.2

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
