name: intl_messages
description: Simple and easy internationalization and localization messages framework for Dart (integrated with package 'intl').
version: 1.1.13
homepage: https://github.com/gmpassos/intl_messages

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  intl: ^0.17.0
  resource_portable: ^3.0.0
  enum_to_string: ^2.0.0-nullsafety.1
  swiss_knife: ^3.0.1

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.5
  #test_coverage: ^0.4.2

#dependency_overrides:
#  resource_portable:
#    path: ../resource_portable
#  swiss_knife:
#    path: ../swiss_knife

