name: intl_messages
description: Simple and easy internationalization and localization messages framework for Dart (integrated with package 'intl') and translation tools (integrated with OpenAI and ChatGPT).
version: 2.1.9
homepage: https://github.com/gmpassos/intl_messages

environment:
  sdk: '>=2.18.0 <4.0.0'

executables:
  intl_messages:

dependencies:
  intl: ^0.18.1
  resource_portable: ^3.0.2
  enum_to_string: ^2.0.1
  swiss_knife: ^3.1.5
  async_extension: ^1.1.0
  yaml: ^3.1.2
  args: ^2.4.1
  path: ^1.8.3
  collection: ^1.17.1
  dart_openai: ^1.9.91

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.1
  pubspec: ^2.3.0
  dependency_validator: ^3.2.2
  coverage: ^1.6.3


#dependency_overrides:
#  resource_portable:
#    path: ../resource_portable
#  swiss_knife:
#    path: ../swiss_knife

