name: intl_messages
description: Simple and easy internationalization and localization messages framework for Dart (integrated with package 'intl') and translation tools (integrated with OpenAI and ChatGPT).
version: 2.3.4
homepage: https://github.com/gmpassos/intl_messages

environment:
  sdk: '>=3.3.0 <4.0.0'

executables:
  intl_messages:

dependencies:
  swiss_knife: ^3.2.2
  async_extension: ^1.2.12
  intl: ^0.19.0
  resource_portable: ^3.1.0
  enum_to_string: ^2.0.1
  yaml: ^3.1.2
  args: ^2.5.0
  path: ^1.9.0
  collection: ^1.18.0
  dart_openai: ^4.1.4

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.8
  pubspec: ^2.3.0
  dependency_validator: ^3.2.3
  coverage: ^1.9.2


#dependency_overrides:
#  resource_portable:
#    path: ../resource_portable
#  swiss_knife:
#    path: ../swiss_knife

