name: intl_messages
description: Simple and easy internationalization and localization messages framework for Dart (integrated with package 'intl') and translation tools (integrated with OpenAI and ChatGPT).
version: 2.3.7
homepage: https://github.com/gmpassos/intl_messages

environment:
  sdk: '>=3.6.0 <4.0.0'

executables:
  intl_messages:

dependencies:
  swiss_knife: ^3.3.3
  async_extension: ^1.2.15
  intl: ^0.20.2
  resource_portable: ^3.1.2
  yaml: ^3.1.3
  args: ^2.7.0
  path: ^1.9.1
  collection: ^1.19.0
  dart_openai: ^4.1.4

dev_dependencies:
  lints: ^5.1.1
  test: ^1.26.3
  pubspec: ^2.3.0
  dependency_validator: ^3.2.3
  coverage: ^1.15.0


#dependency_overrides:
#  resource_portable:
#    path: ../resource_portable
#  swiss_knife:
#    path: ../swiss_knife

