name: intl_messages
description: Simple and easy internationalization and localization messages framework for Dart (integrated with package 'intl').
version: 1.1.12
homepage: https://github.com/gmpassos/intl_messages

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  intl: ^0.16.1
  resource_portable: ^2.1.8
    #path: ../resource_portable
  enum_to_string: ^1.0.8
  swiss_knife: ^2.5.18
    #path: ../swiss_knife

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.3
  test_coverage: ^0.4.2

