name: intl_messages
description: Simple and easy internationalization and localization messages framework for Dart (integrated with package 'intl').
version: 2.0.6
homepage: https://github.com/gmpassos/intl_messages

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  intl: ^0.18.0
  resource_portable: ^3.0.0
  enum_to_string: ^2.0.1
  swiss_knife: ^3.1.3
  async_extension: ^1.1.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.23.1
  dependency_validator: ^3.2.2
  coverage: ^1.6.3


#dependency_overrides:
#  resource_portable:
#    path: ../resource_portable
#  swiss_knife:
#    path: ../swiss_knife

